version: '3'
services:
  rancher-server:
    image: rancher/rancher:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Europe/Istanbul
